version: '3.7'

services:
  api:
    restart: always
    build:
      context: .
      target: builder
    container_name: "goBackend"
    environment:
      - PORT=:8080
    ports:
      - "8080:8080"
    expose:
      - "8080"
